#!/usr/bin/ruby
## $Id$

## Copyright (C) 2006 Daigo Moriwaki <daigo at debian dot org>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#
# This generates html pages from players.yaml.
#
# Sample:
#   $ ./mk_html < players.yaml > rating.html
#   

require 'yaml'
require 'erb'

include ERB::Util

def show_date(time)
  time.strftime("%Y-%m-%d")
end

def usage
  $stderr.puts <<-EOF
USAGE: #{$0} 
  EOF
  exit 1
end

def main
  lines = ""
  while l = gets do
    lines << l
  end
  file = YAML::load(lines)
  erb = ERB.new( DATA.read, nil, "%>" )
  tables = []
  group_names = []
  file["players"].keys.sort.each do |index|
    if index < 999
      group_names << "#{index}"
    else
      group_names << "Not-Yet-Rated Players"
    end
  end

  file["players"].sort.each do |key, yaml| # sort groups in the order written in players.yaml
  sorted_keys = yaml.keys.sort {|a,b| yaml[b]['rate'] <=> yaml[a]['rate']} # sort players in a group by one's rate
  top_rate = nil  
  table = ERB.new(<<ENDTABLE, nil, "%>")
% sorted_keys.each do |key|
  <%
    win  = yaml[key]['win']
    loss = yaml[key]['loss']
    win_rate = win.to_f / (win + loss)
    last_modified = yaml[key]['last_modified']
    
    player_decoration = "default"

    case (Time.now - last_modified)/(60*60*24)
    when (0..1) then player_decoration = "today"
    when (0..7) then player_decoration = "this_week"
    end
    
    case key
    when "yowai_gps+95908f6c18338f5340371f71523fc5e3" then player_decoration = "yowai_gps"
    when "gps+11648e4e66e7ed6a86cb7f1d0cf604fe"       then player_decoration = "gps"
    end

    rate = yaml[key]['rate']
    top_rate ||= rate
    diff_rate = rate - top_rate
    diff_possibility = 1.0/(1.0 + 10**(-diff_rate/400.0))
  %>
  <tr class="<%=player_decoration%>">
    <td class="name">
        <span class="popup"><%= key %></span>
        <%= h yaml[key]['name'] %> </td>
    <td class="rate">
        <span class="popup"><%= "%5d" % [ diff_rate ] %> | <%= "%.3f" % [ diff_possibility ] %></span>
        <%= rate != 0 ? "%5d"  % [ rate ] : "N/A" %> </td>
    <td class="ngames">
        <%= "%5d"  % [ win ] %>  </td>
    <td class="ngames">
        <%= "%5d"  % [ loss ] %> </td>
    <td class="win_rate">
        <%= "%.3f" % [win_rate] %> </td>
    <td class="last_modified">
        <%= show_date(last_modified) %> </td>
  </tr>
% end
ENDTABLE
        
    tables << table.result(binding)
  end

  body = erb.result(binding)
  puts body
end

if __FILE__ == $0
  main
end

# vim: ts=2 sw=2 sts=0

__END__
<html>
<head>
  <title>Shogi Server Rating</title>
  <link rel="StyleSheet" type="text/css" href="http://wdoor.c.u-tokyo.ac.jp/shogi/shogi.css">
  <style type="text/css"><!--
    BODY {margin: 10px 60px;
          text-align: center;}
    TABLE {margin-left: auto;
           margin-right: auto;
           border-collapse: collapse;
           border: solid 2px;
           width: 500px;}
    CAPTION { caption-side: left;}
    TH    {border: solid 1px;}
    TD    {padding-left: 10px;
           padding-right: 10px;
           border: solid 1px;}
    .name {text-align: center;
           width: 180px;}
    .rate, .ngames, .win_rate {text-align: right;}
    .last_modified {text-align: left;}
    .gps, .yowai_gps {background-color: lightgreen;}
    .today     {background-color: #FFD700;}
    .this_week {background-color: #FFDAB9;}

    DIV.footer {text-align: right;
                font-size: 80%;}
    
    TD:hover .popup {
      position: relative;   
      display: inline;
      background-color: #ffffaa;
    }

    .popup { display: none;
             position: absolute;
             top: 1em;
             left: 7em;
             white-space: nowrap;
             border: 1px solid black;
             padding:5px;
             color:black;
             text-decoration:none;
           }
  --></style>
</head>
<body>

<h1>Shogi Server Rating</h1>

% tables.each_with_index do |t, index|
<table>
<caption>Group: <%=group_names[index]%></caption>
<colgroup>
  <col class="name">
  <col class="rate">
  <col class="ngames">
  <col class="ngames">
  <col class="win_rate">
  <col class="last_modified">
</colgroup>
<thead>
<tr>
  <th>name</th>
  <th>rate</th> 
  <th>win</th> 
  <th>loss</th> 
  <th>&#37;</th> 
  <th>last_modified</th>
</tr>
</thead>
<tbody>
  <%= t %>
</tbody>
</table>

<hr style="width:50%; margin:1em auto;">

% end

<p>Groups are independently rated. You can not compare rates across them.
<p>The average of the rates in a group is always 1000. 
<p><a href="http://wdoor.c.u-tokyo.ac.jp/shogi/">BACK</a>

<hr/>

<div class="footer">
  <p>Last modified at <%=Time.now%>
  <p>$Revision$
</div>

</body>
</html>

