#!/usr/bin/ruby
## $Id$

## Copyright (C) 2006 Daigo Moriwaki <daigo at debian dot org>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#
# This generates html pages from players.yaml.
#
# Sample:
#   $ ./mk_html < players.yaml > rating.html
#   

require 'yaml'
require 'erb'

include ERB::Util

def show_date(time)
  time.strftime("%Y-%m-%d")
end

def usage
  $stderr.puts <<-EOF
USAGE: #{$0} 
  EOF
  exit 1
end

def main
  lines = ""
  while l = gets do
    lines << l
  end
  file = YAML::load(lines)
  erb = ERB.new( DATA.read, nil, "%<>" )
  tables = []

  file["players"].each do |key, yaml|
    sorted_keys = yaml.keys.sort {|a,b| yaml[b]['rate'] <=> yaml[a]['rate']}

  table = ERB.new(<<ENDTABLE, nil, "%<>")
<% sorted_keys.each do |key| %>
  <%
    win  = yaml[key]['win']
    loss = yaml[key]['loss']
    win_rate = win.to_f / (win + loss)
    last_modified = yaml[key]['last_modified']
  %>
  <tr>
    <td class="name"><%=h yaml[key]['name']%></td>
    <td class="rate"><%="%5d"  % [ yaml[key]['rate'] ]%></td>
    <td class="ngames"><%="%5d"  % [ win ]%></td>
    <td class="ngames"><%="%5d"  % [ loss ]%></td>
    <td class="win_rate"><%="%.3f" % [win_rate]%></td>
    <td class="last_modified"><%=show_date(last_modified)%></td>
  </tr>
<% end %>
ENDTABLE
        
    tables << table.result(binding)
  end

  body = erb.result(binding)
  puts body
end

if __FILE__ == $0
  main
end

# vim: ts=2 sw=2 sts=0

__END__
<html>
<head>
  <title>Shogi Server Rating</title>
  <link rel="StyleSheet" type="text/css" href="http://wdoor.c.u-tokyo.ac.jp/shogi/shogi.css">
  <style type="text/css"><!--
    BODY {margin: 10px 60px;
          text-align: center;}
    TABLE {margin-left: auto;
           margin-right: auto;
           border-collapse: collapse;
           border: solid 2px;}
    TH    {border: solid 1px;}
    TD    {padding-left: 10px;
           padding-right: 10px;
           border: solid 1px;}
    .name {text-align: center;}
    .rate, .ngames, .win_rate {text-align: right;}
    .last_modified {text-align: left;}

    P.footer {text-align: right;
             font-size: 80%;}
     
  --></style>
</head>
<body>

<h1>Shogi Server Rating</h1>

<% tables.each do |t| %>
<table>
<colgroup>
  <col class="name">
  <col class="rate">
  <col class="ngames">
  <col class="ngames">
  <col class="win_rate">
  <col class="last_modified">
</colgroup>
<thead>
<tr>
  <th>name</th> <th>rate</th> <th>win</th> <th>loss</th> <th>win_rate</th> <th>last_modified</th>
</tr>
</thead>
<tbody>
<%= t %>
</tbody>
</table>
<% end %>

<p>The average of the rates is always 1000. 

<hr/>
<p class="footer">Last modified at <%=Time.now%>

</body>
</html>

